src/Store/Store.WebMVC/Controllers/Admin/FoodController.cs
using AutoMapper;
using Store.BLL.DTO;
using Store.BLL.Interfaces;
using Store.WebMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Store.WebMVC.Controllers.Admin
{
    [Authorize(Roles = "admin")]
    public class FoodController : Controller
    {
        private IFoodService _foodService;
        private ICategoryService _categoryService;

        public FoodController(IFoodService bookService, ICategoryService categoryService)
        {
            _categoryService = categoryService;
            _foodService = bookService;
        }

        public ActionResult Main()
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<FoodDTO, FoodViewModel>()).CreateMapper();
            var foods = _foodService.GetFoods();

            return View(foods);
        }



        public ActionResult GetAllFoods()
        {
            var foods = _foodService.GetFoods();
            return PartialView("ShowFoods", foods);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var food = _foodService.GetFood(id);
            _foodService.DeleteFood(id);
            var foods = _foodService.GetFoods();
            return PartialView("ShowFoods", foods);
        }

        public ActionResult Edit(int id)
        {
            var food = _foodService.GetFood(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<FoodDTO, CreateFoodViewModel>()).CreateMapper();
            var viewModel = mapper.Map<FoodDTO, CreateFoodViewModel>(food);
            viewModel.Categories = new SelectList(_categoryService.GetCategories(), "Id", "CategoryName");
            return PartialView(viewModel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CreateFoodViewModel viewModel, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    viewModel.ImageMimeType = image.ContentType;
                    viewModel.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(viewModel.ImageData, 0, image.ContentLength);
                }

                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CreateFoodViewModel, FoodDTO>()).CreateMapper();
                var foodDTO = mapper.Map<CreateFoodViewModel, FoodDTO>(viewModel);
                _foodService.Update(foodDTO);
                var foods = _foodService.GetFoods();

                return PartialView("ShowFoods", foods);

            }
            else
            {
                ModelState.AddModelError("", "Data filled out incorrectly");
            }
            viewModel.Categories = new SelectList(_categoryService.GetCategories(), "Id", "CategoryName");
            return PartialView("Edit", viewModel);

        }

        public FileContentResult GetImage(int id)
        {
            var food = _foodService.GetFood(id);

            if (food != null & food.ImageData != null
                & food.ImageMimeType != null & food.ImageMimeType != "")
            {
                return File(food.ImageData, food.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult Create()
        {

            CreateFoodViewModel viewModel = new CreateFoodViewModel
            {
                Categories = new SelectList(_categoryService.GetCategories(), "Id", "CategoryName")
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateFoodViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                FoodDTO foodDTO = new FoodDTO
                {
                    Id = viewModel.Id,
                    Name = viewModel.Name,
                    Price = viewModel.Price,
                    CategoryId = viewModel.CategoryId,
                    Description = viewModel.Description,
                };

                _foodService.CreateFood(foodDTO);
                return RedirectToAction("Main");
            }
            else
            {
                ModelState.AddModelError("", "The entered data is incorrect");
            }

            return View(viewModel);
        }
    }
}

src/Store/Store.WebMVC/Controllers/NavController.cs
using Store.BLL.Interfaces;
using Store.WebMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Store.WebMVC.Controllers
{
    public class NavController : Controller
    {
        private IOrderService _orderService;
        private ICategoryService _categoryService;
        public NavController(IOrderService orderService, ICategoryService categoryService)
        {
            _categoryService = categoryService;
            _orderService = orderService;
        }

        public ActionResult GetNav(string category = null)
        {
            var categories = _categoryService.GetCategories();
            MenuViewModel viewModel = new MenuViewModel
            {
                Categories = categories.ToList()
            };
            ViewBag.SelectedCategegory = category;
            return PartialView(viewModel);
        }
    }
}

src/Store/Store.WebMVC/Controllers/ShoppingCartController.cs
using Store.BLL.Interfaces;
using Store.WebMVC.Models;
using Store.WebMVC.Models.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Store.WebMVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        IOrderService orderService;
        private readonly ShoppingCartFactory shoppingCartFactory;

        public ShoppingCartController(IOrderService service, ShoppingCartFactory factory)
        {
            orderService = service;
            shoppingCartFactory = factory;
        }

        public async Task<ActionResult> Index(string returnUrl, Controller controller)
        {

            var cartId = shoppingCartFactory.GetCart(HttpContext);
            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = await orderService.GetAllCartItems(cartId.ShoppingCartId),
                returnUrl = returnUrl,
                CartTotal = await orderService.GetTotal(cartId.ShoppingCartId)
            };
            return View(viewModel);
        }



        public async Task<ActionResult> RemoveFromCart(int id)
        {
            var cartId = shoppingCartFactory.GetCart(this.HttpContext).ShoppingCartId;
            orderService.RemoveFromCart(id, cartId);
            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = await orderService.GetAllCartItems(cartId),
                CartTotal = await orderService.GetTotal(cartId)
            };
            return PartialView("ShowCart", viewModel);

        }
        public async Task<ActionResult> EmptyCart()
        {
            var cartId = shoppingCartFactory.GetCart(this.HttpContext).ShoppingCartId;
            var CartItems = await orderService.GetAllCartItems(cartId);
            if (CartItems.Count == 0)
            {
                ModelState.AddModelError("", "Ваша корзина пуста");
            }
            await orderService.EmptyCart(cartId);
            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = await orderService.GetAllCartItems(cartId),
                CartTotal = await orderService.GetTotal(cartId)
            };
            return PartialView("ShowCart", viewModel);
        }
    }
}

src/Store/Store.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FoodStore</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-dark bg-primary navbar-expand-lg fixed-top">
            <a href="#" class="navbar-brand">FoodStore</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                </ul>
                @using (Html.BeginForm("Index", "Home", FormMethod.Get, new { @class = "form-inline" }))
                {
                    <input class="form-control mr-sm-2" placeholder="Product's name" data-autocomplete-source='@Url.Action("Autocomplete", "Home")' name="searchName" />
                    <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                }
                @if (!User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Login", "Login", "Account", null, new { @class = "btn-outline-light btn ml-1" })
                }
                else
                {
                    @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "btn-outline-light btn ml-1" })
                }
                @if (User.IsInRole("admin"))
                {
                    @Html.ActionLink("Admin Panel", "Main", "Food", null, new { @class = "btn btn-outline-light ml-1" })
                }

                <a class="btn btn-outline-light mx-1" href="@Url.Action("Index","ShoppingCart",  new { returnUrl = Request.Url.PathAndQuery })">
                    <i class="fas fa-shopping-cart mr-1"></i>Cart
                </a>

            </div>
        </nav>

   


    <section class="container-fluid mt-2">
        <div class="row">
            <div class="col-sm-2">
                @Html.Action("GetNav", "Nav")
            </div>
            <div class="col-sm-10">@RenderBody()</div>
        </div>
    </section>

    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>