src/Store/Store.WebMVC/Models/Cart/ShoppingCart.cs
using Store.BLL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Store.WebMVC.Models.Cart
{
    public class ShoppingCart
    {
        private readonly IOrderService orderService;
        public string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        public ShoppingCart(IOrderService service)
        {
            orderService = service;
        }

        public string GetCardId(HttpContextBase context)
        {
            if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
            {
                context.Session[CartSessionKey] = context.User.Identity.Name;
            }
            else
            {
                var cartId = context.Session[CartSessionKey];
                if (cartId == null)
                {
                    cartId = Guid.NewGuid().ToString();
                    context.Session[CartSessionKey] = cartId;
                }
            }
            return context.Session[CartSessionKey].ToString();

        }
    }
}

src/Store/Store.WebMVC/Models/ShoppingCartViewModel.cs
using Store.BLL.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Store.WebMVC.Models
{
    public class ShoppingCartViewModel
    {
        public List<CartItemDTO> CartItems { get; set; }
        public string returnUrl { get; set; }
        public decimal CartTotal { get; set; }
    }
}

src/Store/Store.WebMVC/Controllers/CheckoutController.cs
using Store.BLL.DTO;
using Store.BLL.Interfaces;
using Store.WebMVC.Models;
using Store.WebMVC.Models.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Store.WebMVC.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private readonly IOrderService orderSerivce;
        private readonly ShoppingCartFactory shoppingCartFactory;

        public CheckoutController(IOrderService service, ShoppingCartFactory factory)
        {
            shoppingCartFactory = factory;
            orderSerivce = service;
        }

        [HttpGet]
        public ActionResult MakeOrder()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> MakeOrder(OrderViewModel model)
        {
            var order = new OrderDTO();
            if (ModelState.IsValid)
            {
                TryUpdateModel(order);
                order.UserName = User.Identity.Name;
                order.OrderDate = DateTime.Now;
                var cart = shoppingCartFactory.GetCart(this.HttpContext);
                await orderSerivce.CreateNewOrder(order, cart.ShoppingCartId);
                return RedirectToAction("Complete");
            }

            return View(model);

        }
        public ActionResult Complete(string name, string lname)
        {
            ViewBag.name = name;
            ViewBag.lname = lname;
            return View();
        }
    }
}

src/Store/Store.WebMVC/Controllers/ShoppingCartController.cs
using Store.BLL.Interfaces;
using Store.WebMVC.Models;
using Store.WebMVC.Models.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Store.WebMVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        IOrderService orderService;
        private readonly ShoppingCartFactory shoppingCartFactory;

        public ShoppingCartController(IOrderService service, ShoppingCartFactory factory)
        {
            orderService = service;
            shoppingCartFactory = factory;
        }

        public async Task<ActionResult> Index(string returnUrl, Controller controller)
        {

            var cartId = shoppingCartFactory.GetCart(HttpContext);
            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = await orderService.GetAllCartItems(cartId.ShoppingCartId),
                returnUrl = returnUrl,
                CartTotal = await orderService.GetTotal(cartId.ShoppingCartId)
            };
            return View(viewModel);
        }



        public async Task<ActionResult> RemoveFromCart(int id)
        {
            var cartId = shoppingCartFactory.GetCart(this.HttpContext).ShoppingCartId;
            orderService.RemoveFromCart(id, cartId);
            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = await orderService.GetAllCartItems(cartId),
                CartTotal = await orderService.GetTotal(cartId)
            };
            return PartialView("ShowCart", viewModel);

        }
        public async Task<ActionResult> EmptyCart()
        {
            var cartId = shoppingCartFactory.GetCart(this.HttpContext).ShoppingCartId;
            var CartItems = await orderService.GetAllCartItems(cartId);
            if (CartItems.Count == 0)
            {
                ModelState.AddModelError("", "Ваша корзина пуста");
            }
            await orderService.EmptyCart(cartId);
            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = await orderService.GetAllCartItems(cartId),
                CartTotal = await orderService.GetTotal(cartId)
            };
            return PartialView("ShowCart", viewModel);
        }
    }
}

src/Store/Store.WebMVC/Views/ShoppingCart/Index.cshtml
@{
    ViewBag.Title = "Shopping cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ваша корзина</h2>

<div id="updateCart">
    @Html.Partial("ShowCart")
</div>
<a class="btn btn-primary btn-sm" href="@Model.returnUrl">Continue Shopping</a>
@Ajax.ActionLink("Empty trash", "EmptyCart", "ShoppingCart", null, new AjaxOptions
{
    HttpMethod = "GET",
    UpdateTargetId = "updateCart",
    Confirm = "Do you want to completely empty the trash?"
}, new { @class = "btn btn-primary btn-sm" })
@Html.ActionLink("Place an Order", "MakeOrder", "Checkout", null, new { @class = "btn btn-primary btn-sm" })

src/Store/Store.WebMVC/Views/ShoppingCart/ShowCart.cshtml
@model Store.WebMVC.Models.ShoppingCartViewModel

<table class="table">
    <thead>
        <tr>
            <th>Count</th>
            <th>Position</th>
            <th>Price</th>
            <th>Total price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.CartItems)
        {
            <tr>
                <td>@line.Count</td>
                <td>@line.Food.Name</td>
                <td>@line.Food.Price.ToString("# rub")</td>
                <td>@((line.Food.Price * line.Count).ToString("# rub"))</td>
                <td>
                    @Ajax.ActionLink("Remove", "RemoveFromCart", "ShoppingCart",
                   new { id = line.CartItemId, returnUrl = Model.returnUrl }, new AjaxOptions
                        {
                            HttpMethod = "GET",
                            UpdateTargetId = "updateCart"
                   }, new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Итоге:</td>
            <td>
                @Model.CartTotal.ToString("# rub")
            </td>
        </tr>
    </tfoot>
</table>